---
title: "Q5"
author: "Tejal Kolte"
date: "2023-03-13"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set up

```{r}
# Set up
library(tidyverse)
library(lmtest)
library(sandwich)


setwd("C:/Users/tejal/OneDrive/Desktop/UW/Data 557/Project")
```

## Data Cleaning

```{r}
# Import King County file
accidents_data <- read.csv('US_Accidents_King_County.csv')

# Clean data to use
accidents_data_clean <- accidents_data %>%
  mutate(Amenity=ifelse(Amenity=='False',0,1)) %>%
  mutate(Bump=ifelse(Bump=='False',0,1)) %>%
  mutate(Crossing=ifelse(Crossing=='False',0,1)) %>%
  mutate(Give_Way=ifelse(Give_Way=='False',0,1)) %>%
  mutate(Junction=ifelse(Junction=='False',0,1)) %>%
  mutate(No_Exit=ifelse(No_Exit=='False',0,1)) %>%
  mutate(Railway=ifelse(Railway=='False',0,1)) %>%
  mutate(Roundabout=ifelse(Roundabout=='False',0,1)) %>%
  mutate(Stop=ifelse(Stop=='False',0,1)) %>%
  mutate(Station=ifelse(Station=='False',0,1)) %>%
  mutate(Turning_Loop=ifelse(Turning_Loop=='False',0,1)) %>%
  mutate(Traffic_Calming=ifelse(Traffic_Calming=='False',0,1)) %>%
  mutate(Traffic_Signal=ifelse(Traffic_Signal=='False',0,1)) %>%
  mutate(Sunrise_Sunset=ifelse(Sunrise_Sunset=='Day',0,1)) %>%
  mutate(Civil_Twilight=ifelse(Civil_Twilight=='Day',0,1)) %>%
  mutate(Nautical_Twilight=ifelse(Nautical_Twilight=='Day',0,1)) %>%
  mutate(Astronomical_Twilight=ifelse(Astronomical_Twilight=='Day',0,1))

# Replace 0 with NA so no issues when taking the log
accidents_data_clean$Distance.mi.<- na_if(accidents_data_clean$Distance.mi., 0)

```

## Model 1: Full Model

```{r}
### MODEL 1: Full model (possible)
fit_full_dist <- lm(log(Distance.mi.)~Severity+Side+Temperature.F.+
                      Wind_Chill.F.+Humidity...+Pressure.in.+
                      Visibility.mi.+Wind_Speed.mph.+Amenity+Bump+
                      Crossing+Give_Way+Junction+No_Exit+Railway+Roundabout+Station+
                      Stop+Traffic_Calming+Traffic_Signal+Turning_Loop+
                      Civil_Twilight+Nautical_Twilight+Astronomical_Twilight+
                      Sunrise_Sunset+weekday+hours,data=accidents_data_clean)

coeftest(fit_full_dist, vcov = vcovHC)

# Confidence Interval
`97.5%` <- (coeftest(fit_full_dist, vcov = vcovHC)[,2]*1.96) + 
  coeftest(fit_full_dist, vcov = vcovHC)[,1]
`2.5%` <- (coeftest(fit_full_dist, vcov = vcovHC)[,2]*(-1.96)) + 
  coeftest(fit_full_dist, vcov = vcovHC)[,1]

cbind(`2.5%`,`97.5%`)

# Check assumptions

# Normality
hist(fit_full_dist$residuals,main='Histogram of Residuals')

qqnorm(fit_full_dist$residuals, pch = 1, frame = FALSE)
qqline(fit_full_dist$residuals, col = "blue", lwd = 2)


# Constant Variance
# Constant variance assumption is not met

plot(fit_full_dist$residuals~fit_full_dist$fitted,type='p',
     xlab='Fitted Values',ylab='Residuals',main='Residuals vs Fitted Values')
abline(h=0,col='blue',lty=2)

# Look at residuals vs some predictors


# Pressure
plot(fit_full_dist$residuals~fit_full_dist$model$Pressure.in.,type='p',
     xlab='Pressure',main='Residuals vs Pressure')
abline(h=0,col='blue',lty=2)

# Temperature
plot(fit_full_dist$residuals~fit_full_dist$model$Temperature.F.,type='p',
     xlab='Temperature',main='Residuals vs Temperature')
abline(h=0,col='blue',lty=2)

# Humidity
plot(fit_full_dist$residuals~fit_full_dist$model$Humidity...,type='p',
     xlab='Humidity',main='Residuals vs Humidity')
abline(h=0,col='blue',lty=2)

# Hours
plot(fit_full_dist$residuals~fit_full_dist$model$hours,type='p',
     xlab='Hours',main='Residuals vs Hours')
abline(h=0,col='blue',lty=2)

# Linearity
# Fitted vs. residuals plot seems to have a mean around 0 so linearity is met 
# We will use robust standard errors to deal with the constant variance issues

```

## Global F-test

```{r}
# Model with no predictors
fit_red_0 <- lm(`log(Distance.mi.)` ~ 1, data=fit_full_dist$model)

# Global F-test
waldtest(fit_red_0, fit_full_dist,vcov=vcovHC)

```

## Model 2: Reduced Model

```{r}
### MODEL 2: Reduced model

fit_reduced_dist <- lm(`log(Distance.mi.)`~Severity+Side+Temperature.F.+
                         Wind_Chill.F.+Humidity...+Pressure.in.+
                         Amenity+Crossing+No_Exit+Roundabout+Station+Stop+
                         Traffic_Signal+Astronomical_Twilight+
                         weekday+hours,data=fit_full_dist$model)



coeftest(fit_reduced_dist, vcov = vcovHC)

# Confidence Interval
`97.5%` <- (coeftest(fit_reduced_dist, vcov = vcovHC)[,2]*1.96) + 
  coeftest(fit_reduced_dist, vcov = vcovHC)[,1]
`2.5%` <- (coeftest(fit_reduced_dist, vcov = vcovHC)[,2]*(-1.96)) + 
  coeftest(fit_reduced_dist, vcov = vcovHC)[,1]

cbind(`2.5%`,`97.5%`)


# Check assumptions (fit_reduced_dist)

# Normality
hist(fit_reduced_dist$residuals)

qqnorm(fit_reduced_dist$residuals, pch = 1, frame = FALSE)
qqline(fit_reduced_dist$residuals, col = "blue", lwd = 2)

# Constant Variance
# Constant variance assumption is not met

plot(fit_reduced_dist$residuals~fit_reduced_dist$fitted,type='p',
     xlab='Linear Predictor',main='Residuals vs Fitted Values')
abline(h=0,col='blue',lty=2)

# Look at residuals vs some predictors

# Pressure
plot(fit_reduced_dist$residuals~fit_reduced_dist$model$Pressure.in.,type='p',
     xlab='Pressure',main='Residuals vs Pressure')
abline(h=0,col='blue',lty=2)

# Temperature
plot(fit_reduced_dist$residuals~fit_reduced_dist$model$Temperature.F.,type='p',
     xlab='Temperature',main='Residuals vs Temperature')
abline(h=0,col='blue',lty=2)

# Humidity
plot(fit_reduced_dist$residuals~fit_reduced_dist$model$Humidity...,type='p',
     xlab='Humidity',main='Residuals vs Humidity')
abline(h=0,col='blue',lty=2)

# Hours
plot(fit_reduced_dist$residuals~fit_reduced_dist$model$hours,type='p',
     xlab='Hours',main='Residuals vs Hours')
abline(h=0,col='blue',lty=2)

# Linearity
# Fitted vs. residuals plot seems to have a mean around 0 so linearity is met 
# We will use robust standard errors to deal with the constant variance issues

```

## Model 3: Further Reduced Model

```{r}
### MODEL 3: Further Reduced model

# Does not include any type of road signs or structures
fit_reduced_dist_extra <- lm(`log(Distance.mi.)`~Severity+Temperature.F.+
                               Wind_Chill.F.+Humidity...+Pressure.in.+
                               Astronomical_Twilight+
                               weekday+hours,data=fit_reduced_dist$model)


coeftest(fit_reduced_dist_extra, vcov = vcovHC)


# Confidence Interval
`97.5%` <- (coeftest(fit_reduced_dist_extra, vcov = vcovHC)[,2]*1.96) + 
  coeftest(fit_reduced_dist_extra, vcov = vcovHC)[,1]
`2.5%` <- (coeftest(fit_reduced_dist_extra, vcov = vcovHC)[,2]*(-1.96)) + 
  coeftest(fit_reduced_dist_extra, vcov = vcovHC)[,1]

cbind(`2.5%`,`97.5%`)


# Check assumptions (fit_reduced_dist_extra)

# Normality
hist(fit_reduced_dist_extra$residuals)

qqnorm(fit_reduced_dist_extra$residuals, pch = 1, frame = FALSE)
qqline(fit_reduced_dist_extra$residuals, col = "blue", lwd = 2)

# Constant Variance
plot(fit_reduced_dist_extra$residuals~fit_reduced_dist_extra$fitted,type='p',
     xlab='Linear Predictor',main='Residuals vs Fitted Values',ylim=c(-6,6))
abline(h=0,col='blue',lty=2)

# Look at residuals vs some predictors

# Pressure
plot(fit_reduced_dist_extra$residuals~fit_reduced_dist_extra$model$Pressure.in.,type='p',
     xlab='Pressure',main='Residuals vs Pressure')
abline(h=0,col='blue',lty=2)

# Temperature
plot(fit_reduced_dist_extra$residuals~fit_reduced_dist_extra$model$Temperature.F.,type='p',
     xlab='Temperature',main='Residuals vs Temperature')
abline(h=0,col='blue',lty=2)

# Humidity
plot(fit_reduced_dist_extra$residuals~fit_reduced_dist_extra$model$Humidity...,type='p',
     xlab='Humidity',main='Residuals vs Humidity')
abline(h=0,col='blue',lty=2)

# Hours
plot(fit_reduced_dist_extra$residuals~fit_reduced_dist_extra$model$hours,type='p',
     xlab='Hours',main='Residuals vs Hours')
abline(h=0,col='blue',lty=2)


# Linearity
# Fitted vs. residuals plot seems to have a mean around 0 so linearity is met 
# We will use robust standard errors to deal with the constant variance issues

```

## Multiple F-Tests

```{r}
### Multiple F-tests (robust standard errors)

# Compare full model to reduced model
# Not significant, use reduced model (MODEL 2)
waldtest(fit_reduced_dist, fit_full_dist,vcov=vcovHC)

# Compare reduced model to further reduced model
# Significant, use reduced model (MODEL 2)
waldtest(fit_reduced_dist_extra, fit_reduced_dist,vcov=vcovHC)
```

## Adjusted R-squared

```{r}
summary(fit_full_dist) # Adjusted R-squared:  0.1863
summary(fit_reduced_dist) # Adjusted R-squared:  0.1856
summary(fit_reduced_dist_extra) # Adjusted R-squared:  0.03513
```
